### PR TITLE
Resolve #31

### LINKED ISSUE #31: Implement Worker order handling
With the Strategist created in #12, we now are able to issue orders to units. All unit wrappers can call upon the Strategist's `getUnitOrder(BWAPI::UnitType type)` method to retrieve the next possible build to perform. A Worker should only be asking for a build order when they are not busy. Any build that fails should not be discarded, but retried(possibly double checking that a building does not already exist in that location).

To retrieve a building location, you can use `BWEB` to retrieve a location. `BWEB`'s functions for `onUnitDiscover`, `onUnitMorph`, etc. should also be added to Module to properly keep track of what is where in the map as well.

### PR DESCRIPTION
**Pull request by 0x416C657852**
Resolve #31

### CODE REVIEW

File: src/Units/NonArmyWrappers/WorkerWrapper.cpp [hunk 1]
```diff
@@ -1,24 +1,60 @@
...
+            { // move to the tile
+                this->unit->move(BWAPI::Position(*(tiles.begin())));
+            }
+        }
+    }
+    else if (this->currJob == Jobs::None)
+    { // if slacking, go dig
+        for (const auto &i : BWAPI::Broodwar->getMinerals())
+        { // find closest mineral
+            if (this->unit->getDistance(i) < smallestDistance)
```
Comment (krogenth) [inline src/Units/NonArmyWrappers/WorkerWrapper.cpp]: we can get rid of the need for `smallestDistance`, and instead do an if else:
- if closest isn't null, and the unit's distance to the current mineral is less than the distance to closest
- else if closest is null

File: src/Units/NonArmyWrappers/WorkerWrapper.cpp [hunk 2]
```diff
@@ -1,24 +1,60 @@
...
+            {
                 smallestDistance = this->unit->getDistance(i);
                 closest = i;
             }
         }
         if (closest)
```
Comment (krogenth) [inline src/Units/NonArmyWrappers/WorkerWrapper.cpp]: can reduce this down to a single if statement:
`if (closest && this->unit->gather(closest))`

File: src/Units/NonArmyWrappers/WorkerWrapper.cpp [hunk 3]
```diff
@@ -1,24 +1,60 @@
 #include "./WorkerWrapper.h"
+#include "../../Strategist/Strategist.h"
+#include "BWEB.h"
+
+void WorkerWrapper::onFrame()
+{
 
-void WorkerWrapper::onFrame() {
     BWAPI::Unit closest = nullptr;
```
Comment (krogenth) [inline src/Units/NonArmyWrappers/WorkerWrapper.cpp]: I'd prefer this to be defined within the else path, since it is at least currently only used for finding the nearest mineral patch.

File: src/Units/NonArmyWrappers/WorkerWrapper.cpp [hunk 4]
```diff
@@ -1,24 +1,60 @@
...
+        {                      // store results
+            this->buildOrder = order.value();
+            this->currJob = Jobs::MorphIntoNewBuildings;
+        }
+    }
+
+    // not busy + build order
+    if (this->buildOrder != BWAPI::UnitTypes::Unknown && !this->isBusy())
+    { // get closest bweb block to the starting location of the right size
+        auto tiles = BWEB::Blocks::getClosestBlock(BWAPI::Broodwar->self()->getStartLocation())->getPlacements(this->buildOrder);
```
Comment (krogenth) [inline src/Units/NonArmyWrappers/WorkerWrapper.cpp]: There are going to be issues with this once we get the strategist to make decisions. Since you're only grabbing the nearest block to the starting point, it will grab the same block every time. We can test this using a build order that creates multiple buildings, like:
```
    {BWAPI::UnitTypes::Zerg_Drone, 8},
    {BWAPI::UnitTypes::Zerg_Spawning_Pool, 10},
    {BWAPI::UnitTypes::Zerg_Drone, 8},
    {BWAPI::UnitTypes::Zerg_Drone, 10},
    {BWAPI::UnitTypes::Zerg_Zergling, 12},
    {BWAPI::UnitTypes::Zerg_Zergling, 14},
    {BWAPI::UnitTypes::Zerg_Zergling, 16},
    {BWAPI::UnitTypes::Zerg_Overlord, 18},
    {BWAPI::UnitTypes::Zerg_Drone, 18},
    {BWAPI::UnitTypes::Zerg_Drone, 20},
    {BWAPI::UnitTypes::Zerg_Drone, 22},
    {BWAPI::UnitTypes::Zerg_Hatchery, 24},
    {BWAPI::UnitTypes::Zerg_Hatchery, 22}
    ```

**Review by Soulsteeler123 — APPROVED** [review]

**Review by krogenth — APPROVED** [review]
